mainapp/urls.py
from django.contrib import admin
from django.urls import path
from mainapp import views

app_name = 'mainapp'

urlpatterns = [

    path('admin/', admin.site.urls),
    path('introduce/', views.introduce, name='introduce'),
    path('main/', views.main, name='main'),
    path('menu/', views.menu, name='menu'),

]

pachong_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('userapp/', include('userapp.urls')),
    path('mainapp/', include('mainapp.urls')),
]

mainapp/models.py
from django.db import models
# Create your models here.
class Tlist(models.Model):
    id = models.IntegerField(primary_key=True)
    username = models.CharField(max_length=120, blank=True, null=True)
    gender = models.CharField(max_length=20, blank=True, null=True)
    age = models.CharField(max_length=40, blank=True, null=True)
    expect_salary = models.CharField(max_length=60, blank=True, null=True)
    edu_exp = models.CharField(max_length=120, blank=True, null=True)
    work_exp = models.CharField(max_length=20, blank=True, null=True)
    collage = models.CharField(max_length=40, blank=True, null=True)
    professional = models.CharField(max_length=60, blank=True, null=True)
    expect_place = models.CharField(max_length=60, blank=True, null=True)
    expect_job = models.CharField(max_length=60, blank=True, null=True)
    class Meta:
        db_table = 't_resume'


class UserIP(models.Model):
    ip = models.CharField(max_length=100)
    area = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    time_now = models.CharField(max_length=100)
    visited_func = models.CharField(max_length=100)
    count = models.IntegerField()
    class Meta:
        db_table = 't_userip'

mainapp/views.py
from django.core.paginator import Paginator
from django.shortcuts import render
import time
from Crypto.PublicKey import RSA
from Crypto.Cipher import PKCS1_v1_5
import base64
from mainapp.models import Tlist,UserIP
import requests,json,datetime
from redis import Redis
red = Redis(host='192.168.142.16', port=7000)
# red = Redis(host='rm-2ze49vtrw77mca2cebo.mysql.rds.aliyuncs.com', port=6379)

def log(f):
    def inner(*args,**kwargs):
        req = args[0]
        r = f(*args,**kwargs)
        if 'HTTP_X_FORWARDED_FOR' in req.META:  # 获取 ip
            client_ip = req.META['HTTP_X_FORWARDED_FOR']
            client_ip = client_ip.split(",")[0]  # 所以这里是真实的 ip
        else:
            client_ip = req.META['REMOTE_ADDR']  # 这里获得代理 ip


        ip_exist = UserIP.objects.filter(ip=str(client_ip))
        if ip_exist:  # 判断是否存在该 ip
            user_v = ip_exist[0]
            user_v.count += 1
        else:
            user_v = UserIP()
            user_v.ip = client_ip    #ip
            try:
                user_v.area = request1(client_ip)['area']  # 访问地址
            except:
                user_v.area = 'no_area'
            try:
                user_v.location = request1(client_ip)['location']  # 运营商
            except:
                user_v.location = 'no_location'
            user_v.time_now = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')  # 当前时间
            user_v.visited_func = 'Start %s(%s, %s)...' % (f.__name__, args, kwargs)  # 访问的函数及参数
            user_v.count = 1     #计数
        user_v.save()

        print(client_ip,'11111111111111')
        return r
    return inner


def request1(ip,m="GET"):
    url = "http://apis.juhe.cn/ip/ip2addr"
    params = {
        "ip": ip,  # 需要查询的IP地址或域名
        "key": 'cc538d638eca6bd23755dff94a6fb43b',  # 应用APPKEY(应用详细页查询)
        "dtype": "json",  # 返回数据的格式,xml或json，默认json

    }
    if m == "GET":
        res = requests.get(url,params=params).text
        res_j = json.loads(res)
        # print('get',res)
    else:
        res = requests.post(url,params=params).text
        res_j = json.loads(res)
        # print('post',res)

    # content = f.read()
    # res = json.loads(content)
    if res_j:
        error_code = res_j["error_code"]
        if error_code == 0:
            # 成功请求
            return res_j["result"]
        else:
            print("%s:%s" % (res_j["error_code"], res_j["reason"]))
    else:
        print("request api error")



def main(request):
    key = RSA.generate(1024)
    exportKey = key.publickey().exportKey()
    encrypted_key = key.exportKey()
    request.session['privkey'] = bytes.decode(encrypted_key)
    request.session['publickey'] = bytes.decode(exportKey)
    return render(request,'mainapp/main.html')

def introduce(request):
    return render(request,'mainapp/introduce.html')

#解密
def decrypt_password(privkey,param):
    comfirm_param = base64.b64decode(param)
    encrypted_key = RSA.import_key(privkey)
    cipher_rsa2 = PKCS1_v1_5.new(encrypted_key)
    data = cipher_rsa2.decrypt(comfirm_param,None)
    return bytes.decode(data)

dict_ips, time_ips = {}, []
def judge_ip_redis(ip):
    dict_ips = red.get('ip')
    if dict_ips:
        for dict_ip in eval(dict_ips.decode("utf-8")):
            if ip == dict_ip:
                return None
        else:
            return "ok"
    return "ok"

def judge_ip_count(meta):
    ip = meta['HTTP_HOST']
    ip_ok = judge_ip_redis(ip)
    if ip_ok:
        time_ip = time.time()
        time_ips.append(time_ip)
        dict_ips.update({ip:time_ips})
        ip_value = dict_ips.get(ip)
        if len(ip_value) == 5:
            if ip_value[4]-ip_value[0] < 10:
                red.set('ip',dict_ips,ex=20)
                dict_ips.clear()
                time_ips.clear()
                return None
            return 'ok'
        return 'ok'
    return None

@log
def menu(request):
    privkey = request.session.get('privkey')
    publickey = request.session.get('publickey')
    meta = request.META
    try:
        use_ip = judge_ip_count(meta)
        if use_ip:
            select = request.GET.get('select')
            city = request.GET.get('city')
            job = request.GET.get('job')
            number = request.GET.get("number")
            if number:
                number = number.replace(' ', '+')
                number = decrypt_password(privkey,number)
            if not number or not number.isdigit():
                number = 1
            expect_place = request.GET.get('expect_place')
            expect_job = request.GET.get('expect_job')
            if expect_place == 'None':
                expect_place=None
            if expect_job == 'None':
                expect_job=None
            if select:
                if select in "北京beijingbjBJ":
                    expect_place = '北京'
                if select in "上海shanghaiSHsh":
                    expect_place = '上海'
                if select in "广州guangzhougzGZ":
                    expect_place = '广州'
                if select in "深圳shenzhenSZsz":
                    expect_place = '深圳'
                if select in "Python WebPWpwpythonweb":
                    expect_job = 'Python Web'
                if select in "爬虫pachongPC":
                    expect_job = '爬虫'
                if select in "大数据datadashujuDSJ":
                    expect_job = '大数据'
                if select in "AIai人工智能":
                    expect_job = 'AI'
            if city:
                if city in "北京beijingbjBJ":
                    expect_place = '北京'
                if city in "上海shanghaiSHsh":
                    expect_place = '上海'
                if city in "广州guangzhougzGZ":
                    expect_place = '广州'
                if city in "深圳shenzhenSZsz":
                    expect_place = '深圳'
            if job:
                if job in "Python WebPWpwpythonweb":
                    expect_job = 'Python Web'
                if job in "爬虫pachongPC":
                    expect_job = '爬虫'
                if job in "大数据datadashujuDSJ":
                    expect_job = '大数据'
                if job in "AIai人工智能":
                    expect_job = 'AI'
            #查询判断
            print(expect_place,expect_job,number)
            if expect_place and expect_job:
                result = Tlist.objects.filter(expect_place__contains=expect_place,expect_job__contains=expect_job)
            elif not expect_place and expect_job:
                result = Tlist.objects.filter(expect_job__contains=expect_job)
            elif expect_place and not expect_job:
                result = Tlist.objects.filter(expect_place__contains=expect_place)
            else:
                return render(request,'mainapp/menu.html')
            #分页展示
            pagtor = Paginator(result,per_page=15)
            pages = pagtor.page(number)
            all_info = Tlist.objects.all().values()
            a, b, c, d = 0, 0, 0, 0  # a,b,c,d分别代表北上广深
            python_web, spider, bigdata, AI = 0, 0, 0, 0
            for i in all_info:
                # print(i['expect_job'],'5555555555')
                if i['expect_place'] == '北京':
                    a += 1
                elif i['expect_place'] == '上海':
                    b += 1
                elif i['expect_place'] == '广州':
                    c += 1
                elif i['expect_place'] == '深圳':
                    d += 1
                if i['expect_job'] == 'Python Web':
                    python_web += 1
                elif i['expect_job'] == '爬虫':
                    spider += 1
                elif i['expect_job'] == '大数据':
                    bigdata += 1
                elif i['expect_job'] == 'AI':
                    AI += 1
            print(python_web, spider, bigdata, AI, '11111111')
            return render(request, 'mainapp/menu.html',
                          {'pages': pages, 'expect_place': expect_place, 'expect_job': expect_job,'publickey':publickey,
                           'a': a, 'b': b, 'c': c, 'd': d,
                           'python_web': python_web,
                           'spider': spider,
                           'bigdata': bigdata,
                           'AI': AI})
            # return render(request,'mainapp/menu.html',{'pages':pages,'expect_place':expect_place,'expect_job':expect_job,'publickey':publickey})
        return render(request,'mainapp/not_ip.html')
    except:
        dict_ips.clear()
        time_ips.clear()
    # 获取表中所有数据并展示

templates/mainapp/introduce.html
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>百智招聘</title>
<link href="../../static/style/authority/basic_layout.css" rel="stylesheet" type="text/css">
<link href="../../static/style/authority/common_style.css" rel="stylesheet" type="text/css">
</head>
<body>
	<div id="container">
		<table class="table" cellspacing="0" cellpadding="0" width="100%" align="center"  border="0">
		    <tr>
		      <th colspan="2">系统版本</th>
		    </tr>
		    <tr>
		      <td width="100" height="30">当前版本<span class="TableRow2"></span></td>
		      <td style="text-align:left">百智招聘系统 4.1</td>
		    </tr>
		</table>
	</div>
</body>
</html>

templates/mainapp/main.html
<!DOCTYPE html>
{% load static %}
<html lang="zh-CN">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>百智招聘</title>
	<link href="../../static/style/authority/main_css.css" rel="stylesheet" type="text/css" />
	<link href="../../static/style/authority/zTreeStyle.css" rel="stylesheet" type="text/css">
	<script type="text/javascript" src="../../static/scripts/jquery/jquery-1.7.1.js"></script>
	<script type="text/javascript" src="../../static/scripts/zTree/jquery.ztree.core-3.2.js"></script>
	<script type="text/javascript" src="../../static/scripts/authority/commonAll.js"></script>
    <script src="../../static/scripts/echarts.min.js"></script>
	<script type="text/javascript">
		/* zTree插件加载目录的处理  */
		var zTree;
		
		var setting = {
				view: {
					dblClickExpand: false,
					showLine: false,
					expandSpeed: ($.browser.msie && parseInt($.browser.version)<=6)?"":"fast"
				},
				data: {
					key: {
						name: "resourceName"
					},
					simpleData: {
						enable:true,
						idKey: "resourceID",
						pIdKey: "parentID",
						rootPId: ""
					}
				},
				callback: {
	// 				beforeExpand: beforeExpand,
	// 				onExpand: onExpand,
					onClick: zTreeOnClick			
				}
		};
		 
		var curExpandNode = null;
		function beforeExpand(treeId, treeNode) {
			var pNode = curExpandNode ? curExpandNode.getParentNode():null;
			var treeNodeP = treeNode.parentTId ? treeNode.getParentNode():null;
			for(var i=0, l=!treeNodeP ? 0:treeNodeP.children.length; i<l; i++ ) {
				if (treeNode !== treeNodeP.children[i]) {
					zTree.expandNode(treeNodeP.children[i], false);
				}
			}
			while (pNode) {
				if (pNode === treeNode) {
					break;
				}
				pNode = pNode.getParentNode();
			}
			if (!pNode) {
				singlePath(treeNode);
			}
	
		}
		function singlePath(newNode) {
			if (newNode === curExpandNode) return;
			if (curExpandNode && curExpandNode.open==true) {
				if (newNode.parentTId === curExpandNode.parentTId) {
					zTree.expandNode(curExpandNode, false);
				} else {
					var newParents = [];
					while (newNode) {
						newNode = newNode.getParentNode();
						if (newNode === curExpandNode) {
							newParents = null;
							break;
						} else if (newNode) {
							newParents.push(newNode);
						}
					}
					if (newParents!=null) {
						var oldNode = curExpandNode;
						var oldParents = [];
						while (oldNode) {
							oldNode = oldNode.getParentNode();
							if (oldNode) {
								oldParents.push(oldNode);
							}
						}
						if (newParents.length>0) {
							for (var i = Math.min(newParents.length, oldParents.length)-1; i>=0; i--) {
								if (newParents[i] !== oldParents[i]) {
									zTree.expandNode(oldParents[i], false);
									break;
								}
							}
						}else {
							zTree.expandNode(oldParents[oldParents.length-1], false);
						}
					}
				}
			}
			curExpandNode = newNode;
		}
	
		function onExpand(event, treeId, treeNode) {
			curExpandNode = treeNode;
		}
		
		/** 用于捕获节点被点击的事件回调函数  **/
		function zTreeOnClick(event, treeId, treeNode) {
			var zTree = $.fn.zTree.getZTreeObj("dleft_tab1");
			zTree.expandNode(treeNode, null, null, null, true);
	// 		zTree.expandNode(treeNode);
			// 规定：如果是父类节点，不允许单击操作
			if(treeNode.isParent){
	// 			alert("父类节点无法点击哦...");
				return false;
			}
			// 如果节点路径为空或者为"#"，不允许单击操作
			if(treeNode.accessPath=="" || treeNode.accessPath=="#"){
				//alert("节点路径为空或者为'#'哦...");
				return false;
			}
		    // 跳到该节点下对应的路径, 把当前资源ID(resourceID)传到后台，写进Session
		    rightMain(treeNode.accessPath);
		    
		    if( treeNode.isParent ){
			    $('#here_area').html('当前位置：'+treeNode.getParentNode().resourceName+'&nbsp;>&nbsp;<span style="color:#1A5CC6">'+treeNode.resourceName+'</span>');
		    }else{
			    $('#here_area').html('当前位置：系统&nbsp;>&nbsp;<span style="color:#1A5CC6">'+treeNode.resourceName+'</span>');
		    }
		};
		
		/* 上方菜单 */
		function switchTab(tabpage,tabid){
		var oItem = document.getElementById(tabpage).getElementsByTagName("li"); 
		    for(var i=0; i<oItem.length; i++){
		        var x = oItem[i];    
		        x.className = "";
			}
			if('left_tab1' == tabid){
				$(document).ajaxStart(onStart).ajaxSuccess(onStop);
			
			  	loadMenu('YEWUMOKUAI', 'dleft_tab1');
			}else  if('left_tab2' == tabid){
				$(document).ajaxStart(onStart).ajaxSuccess(onStop);
		
				loadMenu('XITONGMOKUAI', 'dleft_tab1');
			}else  if('left_tab3' == tabid){
				$(document).ajaxStart(onStart).ajaxSuccess(onStop);
	
				loadMenu('QITAMOKUAI', 'dleft_tab1');
			} 
		}
		
		
		$(document).ready(function(){
			$(document).ajaxStart(onStart).ajaxSuccess(onStop);

			loadMenu('YEWUMOKUAI', "dleft_tab1");
			// 默认展开所有节点
			if( zTree ){
				// 默认展开所有节点
				zTree.expandAll(true);
			}
		});
		
		function loadMenu(resourceType, treeObj){
			
            data = [ 
			{"accessPath":"","checked":false,"delFlag":0,"parentID":1,"resourceCode":"","resourceDesc":"","resourceGrade":2,"resourceID":3,"resourceName":"北京","resourceOrder":0,"resourceType":""},
            {"accessPath":"","checked":false,"delFlag":0,"parentID":1,"resourceCode":"","resourceDesc":"","resourceGrade":2,"resourceID":4,"resourceName":"上海","resourceOrder":0,"resourceType":""},
            {"accessPath":"","checked":false,"delFlag":0,"parentID":1,"resourceCode":"","resourceDesc":"","resourceGrade":2,"resourceID":5,"resourceName":"广州","resourceOrder":0,"resourceType":""},
            {"accessPath":"","checked":false,"delFlag":0,"parentID":1,"resourceCode":"","resourceDesc":"","resourceGrade":2,"resourceID":6,"resourceName":"深圳","resourceOrder":0,"resourceType":""},

            {"accessPath":"{% url 'mainapp:menu' %}?expect_place=北京&expect_job=Python Web","checked":false,"delFlag":0,"parentID":3,"resourceCode":"","resourceDesc":"","resourceGrade":3,"resourceID":7,"resourceName":"Python Web","resourceOrder":0,"resourceType":""},
            {"accessPath":"{% url 'mainapp:menu' %}?expect_place=北京&expect_job=爬虫","checked":false,"delFlag":0,"parentID":3,"resourceCode":"","resourceDesc":"","resourceGrade":3,"resourceID":8,"resourceName":"爬虫","resourceOrder":0,"resourceType":""},
            {"accessPath":"{% url 'mainapp:menu' %}?expect_place=北京&expect_job=大数据","checked":false,"delFlag":0,"parentID":3,"resourceCode":"","resourceDesc":"","resourceGrade":3,"resourceID":9,"resourceName":"大数据","resourceOrder":0,"resourceType":""},
            {"accessPath":"{% url 'mainapp:menu' %}?expect_place=北京&expect_job=AI","checked":false,"delFlag":0,"parentID":3,"resourceCode":"","resourceDesc":"","resourceGrade":3,"resourceID":10,"resourceName":"AI","resourceOrder":0,"resourceType":""},
			{"accessPath":"{% url 'mainapp:menu' %}?expect_place=上海&expect_job=Python Web","checked":false,"delFlag":0,"parentID":4,"resourceCode":"","resourceDesc":"","resourceGrade":3,"resourceID":11,"resourceName":"Python Web","resourceOrder":0,"resourceType":""},
            {"accessPath":"{% url 'mainapp:menu' %}?expect_place=上海&expect_job=爬虫","checked":false,"delFlag":0,"parentID":4,"resourceCode":"","resourceDesc":"","resourceGrade":3,"resourceID":12,"resourceName":"爬虫","resourceOrder":0,"resourceType":""},
            {"accessPath":"{% url 'mainapp:menu' %}?expect_place=上海&expect_job=大数据","checked":false,"delFlag":0,"parentID":4,"resourceCode":"","resourceDesc":"","resourceGrade":3,"resourceID":13,"resourceName":"大数据","resourceOrder":0,"resourceType":""},
            {"accessPath":"{% url 'mainapp:menu' %}?expect_place=上海&expect_job=AI","checked":false,"delFlag":0,"parentID":4,"resourceCode":"","resourceDesc":"","resourceGrade":3,"resourceID":14,"resourceName":"AI","resourceOrder":0,"resourceType":""},
			{"accessPath":"{% url 'mainapp:menu' %}?expect_place=广州&expect_job=Python Web","checked":false,"delFlag":0,"parentID":5,"resourceCode":"","resourceDesc":"","resourceGrade":3,"resourceID":15,"resourceName":"Python Web","resourceOrder":0,"resourceType":""},
            {"accessPath":"{% url 'mainapp:menu' %}?expect_place=广州&expect_job=爬虫","checked":false,"delFlag":0,"parentID":5,"resourceCode":"","resourceDesc":"","resourceGrade":3,"resourceID":16,"resourceName":"爬虫","resourceOrder":0,"resourceType":""},
            {"accessPath":"{% url 'mainapp:menu' %}?expect_place=广州&expect_job=大数据","checked":false,"delFlag":0,"parentID":5,"resourceCode":"","resourceDesc":"","resourceGrade":3,"resourceID":17,"resourceName":"大数据","resourceOrder":0,"resourceType":""},
            {"accessPath":"{% url 'mainapp:menu' %}?expect_place=广州&expect_job=AI","checked":false,"delFlag":0,"parentID":5,"resourceCode":"","resourceDesc":"","resourceGrade":3,"resourceID":18,"resourceName":"AI","resourceOrder":0,"resourceType":""},
			{"accessPath":"{% url 'mainapp:menu' %}?expect_place=深圳&expect_job=Python Web","checked":false,"delFlag":0,"parentID":6,"resourceCode":"","resourceDesc":"","resourceGrade":3,"resourceID":15,"resourceName":"Python Web","resourceOrder":0,"resourceType":""},
            {"accessPath":"{% url 'mainapp:menu' %}?expect_place=深圳&expect_job=爬虫","checked":false,"delFlag":0,"parentID":6,"resourceCode":"","resourceDesc":"","resourceGrade":3,"resourceID":16,"resourceName":"爬虫","resourceOrder":0,"resourceType":""},
            {"accessPath":"{% url 'mainapp:menu' %}?expect_place=深圳&expect_job=大数据","checked":false,"delFlag":0,"parentID":6,"resourceCode":"","resourceDesc":"","resourceGrade":3,"resourceID":17,"resourceName":"大数据","resourceOrder":0,"resourceType":""},
            {"accessPath":"{% url 'mainapp:menu' %}?expect_place=深圳&expect_job=AI","checked":false,"delFlag":0,"parentID":6,"resourceCode":"","resourceDesc":"","resourceGrade":3,"resourceID":18,"resourceName":"AI","resourceOrder":0,"resourceType":""}];

            if(data != null){
                // 将返回的数据赋给zTree
                $.fn.zTree.init($("#"+treeObj), setting, data);
//              alert(treeObj);
                zTree = $.fn.zTree.getZTreeObj(treeObj);
                if( zTree ){
                    // 默认展开所有节点
                    zTree.expandAll(true);
                }
            }
		}
		
		//ajax start function
		function onStart(){
			$("#ajaxDialog").show();
		}
		
		//ajax stop function
		function onStop(){
	// 		$("#ajaxDialog").dialog("close");
			$("#ajaxDialog").hide();
		}
	</script>
</head>
<body >
    <div id="top">
		<div id="top_logo">
			<img alt="logo" src="../../static/images/common/logo.jpg" width="274" height="49" style="vertical-align:middle;">
		</div>
	</div>
    <!-- side menu start -->
	<div id="side">
		<div id="left_menu">
		 	<ul id="TabPage2" style="height:200px; margin-top:50px;"></ul>
			<div id="nav_show" style="position:absolute; bottom:0px; padding:10px;">
				<a href="javascript:;" id="show_hide_btn">
					<img alt="显示/隐藏" title="显示/隐藏" src="../../static/images/common/nav_hide.png" width="35" height="35">
				</a>
			</div>
		 </div>
		 <div id="left_menu_cnt">
		 	<div id="nav_module">
		 		<img src="../../static/images/common/module_1.png" width="210" height="58"/>
		 	</div>
		 	<div id="nav_resource">
		 		<ul id="dleft_tab1" class="ztree"></ul>
		 	</div>
		 </div>
	</div>
	<script type="text/javascript">
		$(function(){
			$('#TabPage2 li').click(function(){
				var index = $(this).index();
				$(this).find('img').attr('src', 'images/common/'+ (index+1) +'_hover.jpg');
				$(this).css({background:'#fff'});
				$('#nav_module').find('img').attr('src', 'images/common/module_'+ (index+1) +'.png');
				$('#TabPage2 li').each(function(i, ele){
					if( i!=index ){
						$(ele).find('img').attr('src', 'images/common/'+ (i+1) +'.jpg');
						$(ele).css({background:'#044599'});
					}
				});
				// 显示侧边栏
				switchSysBar(true);
			});
			
			// 显示隐藏侧边栏
			$("#show_hide_btn").click(function() {
		        switchSysBar();
		    });
		});
		
		/**隐藏或者显示侧边栏**/
		function switchSysBar(flag){
			var side = $('#side');
	        var left_menu_cnt = $('#left_menu_cnt');
			if( flag==true ){	// flag==true
				left_menu_cnt.show(500, 'linear');
				side.css({width:'280px'});
				$('#top_nav').css({width:'77%', left:'304px'});
	        	$('#main').css({left:'280px'});
			}else{
		        if ( left_menu_cnt.is(":visible") ) {
					left_menu_cnt.hide(10, 'linear');
					side.css({width:'60px'});
		        	$('#top_nav').css({width:'100%', left:'60px', 'padding-left':'28px'});
		        	$('#main').css({left:'60px'});
		        	$("#show_hide_btn").find('img').attr('src', '../../static/images/common/nav_show.png');
		        } else {
					left_menu_cnt.show(500, 'linear');
					side.css({width:'280px'});
					$('#top_nav').css({width:'77%', left:'304px', 'padding-left':'0px'});
		        	$('#main').css({left:'280px'});
		        	$("#show_hide_btn").find('img').attr('src', '../../static/images/common/nav_hide.png');
		        }
			}
		}
	</script>
    <!-- 为ECharts准备一个具备大小（宽高）的Dom -->

    <!-- side menu start -->
    <div id="top_nav">
	 	<span id="here_area">当前位置：系统&nbsp;>&nbsp;系统介绍</span>
	</div>
    <div id="main">
      	<iframe name="right" id="rightMain" src="{% url 'mainapp:introduce' %}" frameborder="no" scrolling="auto" width="100%" height="100%" allowtransparency="true"/>
    </div>
</body>
</html>
   
 