mainapp/urls.py
from django.contrib import admin
from django.urls import path
from mainapp import views

app_name = 'mainapp'

urlpatterns = [

    path('admin/', admin.site.urls),
    path('introduce/', views.introduce, name='introduce'),
    path('main/', views.main, name='main'),
    path('menu/', views.menu, name='menu'),

]

pachong_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('userapp/', include('userapp.urls')),
    path('mainapp/', include('mainapp.urls')),
]

userapp/urls.py
from django.contrib import admin
from django.urls import path
from userapp import views

app_name = 'userapp'

urlpatterns = [

    path('admin/', admin.site.urls),
    path('register/', views.register, name='register'),
    path('name/', views.name, name='name'),
    path('isPhone/', views.isPhone, name='isPhone'),
    path('isEmail/', views.isEmail, name='isEmail'),
    path('pwd/', views.pwd, name='pwd'),
    path('message/', views.message, name='message'),
    path('checkcode/', views.checkcode, name='checkcode'),
    path('registerlogic/', views.registerlogic, name='registerlogic'),
    path('login/', views.login, name='login'),
    path('loginlogic/', views.loginlogic, name='loginlogic'),

]

userapp/models.py
from django.db import models

# Create your models here.


class User_info(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=60)
    phone = models.CharField(max_length=20)
    email = models.CharField(max_length=30)
    password = models.CharField(max_length=30)

userapp/views.py
import re
from django.shortcuts import render,redirect,HttpResponse
from .zhenzismsclient import ZhenziSmsClient
import random
import ssl
# Create your views here.

#注册函数
from userapp.models import User_info


def register(request):
    return render(request,'userapp/register.html')


# 验证用户名是否合格
def name(request):
    name = request.GET.get('name')
    pwd1 = re.match('[^0-9]{1,30}',name)
    if pwd1 == None:
        return HttpResponse('空')
    else:
        return HttpResponse('正确')

# 验证手机号是否存在
def isPhone(request):
    phone = request.GET.get('phone')
    if phone == '':
        return HttpResponse('空')
    else:
        check_phone = re.match('\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*|^1\d{10}',phone)
        if check_phone:
            return HttpResponse('正确')
        return HttpResponse('手机格式有误')

# 验证邮箱是否合法
def isEmail(request):
    email = request.GET.get('email')
    if email == '':
        return HttpResponse('空')
    else:
        check_email = re.match('\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*|^1\d{10}',email)
        if check_email:
            return HttpResponse('正确')
        return HttpResponse('邮箱格式有误')


# 验证密码格式
def pwd(request):
    pwd1 = request.POST.get('pwd1')
    if pwd1 == '':
        return HttpResponse('空')
    elif len(pwd1)>20 or len(pwd1)<6:
        return HttpResponse('长度')
    else:
        check_pwd = re.match(r'^\w{6,20}$',pwd1)
        # print(check_pwd)
        if check_pwd:
            return HttpResponse('正确')
        return HttpResponse('密码格式有误')

# 发送短信验证码
def message(request):
    number = request.GET.get('check_code')
    phone = request.GET.get('phone')
    print(number,phone)
    if number == '1':
        ssl._create_default_https_context = ssl._create_unverified_context
        client = ZhenziSmsClient('https://sms_developer.zhenzikj.com', '101969','292dee41-b7c2-43ea-8ff4-612b7289c0b8')
        num = ''
        for i in range(4):
            num += str(random.randint(0, 9))
        result = client.send(phone, '欢迎注册皮皮官网，您的验证码是：' + num+',请在1分钟内输入验证码.')
        request.session['code'] = num
        print(result)
    return HttpResponse('验证码已发送')

# 判断验证码是否一致
def checkcode(request):
    check = request.GET.get('check')
    print(request.session.get('code'))
    if check == request.session.get('code'):
        return HttpResponse('两相同')
    else:
        return HttpResponse('不相同')

# 二次验证用户注册信息是否合法，不合法不能跳转页面
def registerlogic(request):
    name = request.POST.get('name')
    phone = request.POST.get('phone')
    email = request.POST.get('email')
    password = request.POST.get('password')
    code = request.POST.get('txt_vcode')
    info = User_info.objects.filter(email=email)
    print(name,phone,email,password,code)
    check_name = re.match('[^0-9]{1,30}',name)
    check_phone = re.match('1[^0126]\d{9}',phone)
    check_email = re.match('\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*|^1\d{10}', email)
    check_password = re.match(r'^\w{6,20}$',password)
    if info != None and check_email == None:
        return render(request,'userapp/register.html')
    elif check_phone == None or check_password == None or check_name == None or code != request.session.get('code'):
        return render(request,'userapp/register.html')
    else:
        User_info.objects.create(name=name,phone=phone,email=email,password=password)
        return render(request,'userapp/login.html')


#登录函数
def login(request):
    return render(request,'userapp/login.html')


#登录逻辑函数
def loginlogic(request):
    name = request.POST.get('name')
    # name = request.POST.get('name')
    password = request.POST.get('password')
    print(name,password)
    person_info = User_info.objects.filter(name=name,password=password)
    if person_info:
        return render(request,'mainapp/main.html')
    else:
        return render(request,'userapp/login.html')


# 异步请求

templates/userapp/login.html
<!doctype html>
<html>
<head>
<title>Home</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- font files  -->
<link href='https://fonts.googleapis.com/css?family=Muli:400,300' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Nunito:400,300,700' rel='stylesheet' type='text/css'>
<!-- /font files  -->
<!-- css files -->
<link href="../../static/css/style.css" rel='stylesheet' type='text/css' media="all" />
<!-- /css files -->
{#<script>#}
{#    function login() {#}
{#        var name = document.getElementById('name').value;#}
{#        var password = document.getElementById('password').value;#}
{#        var url = "{% url 'userapp:loginlogic' %}name="+name+'&password='+password;#}
{#        var a;#}
{#        if(window.ActiveXObject){#}
{#            a = new ActiveXObject("Microsoft.XMLHTTP")#}
{#        }else if (window.XMLHttpRequest){#}
{#            a = new XMLHttpRequest()#}
{#        }#}
{#        a.open("get",url,true);#}
{#        a.onreadystatechange = function () {#}
{#            if (a.readyState == 4 && a.status == 200){#}
{#                result = a.responseText;#}
{#                console.log('result=' + result);#}
{#                if (result == '用户名或密码有误，请重新输入'){#}
{#                    document.getElementById('error').innerHTML = "<font color='red' size='2px'>账号或密码有误，请重新输入</font>";#}
{#                }#}
{#            }#}
{#        }#}
{#    }#}
{#</script>#}
</head>
<body>
<h1>Login</h1>
<div class="log">
	<div class="content1">
		<h2>Login</h2>
		<form action="{% url 'userapp:loginlogic' %}" method="post" enctype="application/x-www-form-urlencoded">
            {% csrf_token %}
			<input type="text" name="name" id="name" value="请输入用户名" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'USERNAME';}">
			<input type="password" name="password" id="password" placeholder="请输入密码" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'PASSWORD';}">
			<div id="error"></div>
            <div class="button-row">
				<input type="submit" class="sign-in" value="马上登录">
				<input type="reset" class="reset" value="重置信息">
				<div class="clear"></div>
			</div>

{#		</form>#}
	</div>

	<div class="clear"></div>
</div>
<div class="footer">
	<p>Copyright &copy;  <a href="http://www.baizhiedu.com/" target="_blank" title="百知教育">百知教育</a></p>
</div>

</body>
</html>